search_fail = "No results. Please try again."
exit = "Exiting....\n"
i1 = "\n\nAVANT\n"
i2 = "Random-data generating algorithm for experimental Quake III machinima (post-)production" 
i3 = "Created by Jordy Veenstra / A Pixelated Point of View"
i4 = "\nVersion 0.0.0\n"
sd = "Accessing database...\n"
ad = "Attempting to download external database...\n"
nf = "Database file not found. Looking for external database...\n"
sc = "Found database file!\n"
se = "Could not connect to avant database\n"
sdd = "Succesfully downloaded database file!\n"
cancel_one = "Return to main menu"
cancel_two = "Change project settings and algorithm mode"
cancel_three = "Proceed with current project settings and algorithm mode"
confirm_one = "Please confirm your project settings\n"
confirm_two = "\nAre these settings correct? (Y/N)"
mode_one = "Production Mode (Production data and capturing files)"
mode_two = "Post Mode (Editing data only)"
mode_three = "Full Service mode (Production- and Post Mode combined)"
setup_1 = "Please specify a name for your project (max 30 chars):"
setup_2 = "Your project name must be shorter than 30 characters."
setup_3 = "Please define the framerate of your project (f.e. 24, 25, 29.997, 30, 60 or 23.976):"
setup_4 = "You did not define a valid framerate. Please try again."
setup_5 = "Please select your algorithm mode of choice."
start_algorithm = "Start Algorithm"
help = "Documentation"
help_1 = "DOCUMENTATION"
help_2 = "Find the complete documentation regarding usage, data interpretation,\nfrequently asked questions and updates at https://avant-docs.vercel.app"
credits = "Credits"
exit = "Exit"
exit_two = "Exiting....\n"
cred = "AVANT\nRandom-data generating algorithm for experimental Quake III machinima (post-)production\nCreated by Jordy Veenstra / A Pixelated Point of View\n"
cred_2 = "LINKS/REPOSITORIES:\nGitHub: https://github.com/jiyorude/avant\nIssues: https://github.com/jiyorude/avant/issues\nDocumentation: https://avant-docs.vercel.app\nBitBucket: https://bitbucket.org/appov/avant/src/main/\nPyPi: T.B.A"
cred_3 = "\nSOFTWARE/MODULES:\nPython 3.11 (Python Software Foundation)\nPyMongo (MongoDB Python Team)\nInquirer (Miguel Ángel García)\nReportlab (Andy Robinson, Robin Becker)\nASCII Art Generator (patorjk)\nAvantlib (Jordy Veenstra)\nVertice (Jordy Veenstra)\n\n"
any = "Press ENTER\RETURN to return to the main menu..."
any2 = "SCROLL to read. Press ENTER\RETURN to go back..."
start_1 = "The algorithm starts here..."
post_one = "Succesfully created folder structure in your DOCUMENTS folder.\n"
post_two = "Avant will automatically open your Documents folder in a few seconds.\nOpen the Avant folder, followed by your project folder.\n\nPlease insert your raw footage into the 'FOOTAGE' folder.\nIf you have any image sequences, place them in the 'IMAGE SEQUENCES FOLDER'.\nPress the ENTER/RETURN key in the terminal window once you are ready.\n"
no_files = "No usable Image Sequences nor Video files found. Shutting down Avant..."
ascii = """
      __      __       _   _  _______ 
     /\\ \    / //\    | \ | ||__   __|
    /  \\ \  / //  \   |  \| |   | |   
   / /\ \\ \/ // /\ \  | . ` |   | |   
  / ____ \\  // ____ \ | |\  |   | |   
 /_/    \_\\//_/    \_\|_| \_|   |_|
 """